<?php
/** @noinspection PhpUnused */

use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.37
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class CountryRepo
 */
class CountryRepo extends _BasePdoOneRepo
{
    const TABLE = 'country';
    const PK = 'IdCounty';
    const ME=__CLASS__;

    public static function getDef() {
        return [
            'IdCounty' => 'int not null auto_increment',
            'Name' => 'varchar(45)'
        ];
    }
    public static function getDefKey() {
        return [
            'IdCounty' => 'PRIMARY KEY'
        ];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [

            ];
        }
        /* key,refcol,reftable,extra */
        return [
            '/players' => [
                'key' => 'ONETOMANY',
                'col' => 'IdCounty',
                'reftable' => 'players',
                'refcol' => 'IdCounty'
            ]
        ];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
            'IdCounty'=>0,
            '/players'=>(in_array('/players',$recursive))
                ? []
                : null, /* onetomany */
            'Name'=>''
        ];
    }
    public static function factoryNull() {
        return [
            'IdCounty'=>null,
            'Name'=>null
        ];
    }

}