<?php
/** @noinspection PhpUnused */

use eftec\PdoOne;
use eftec\_BasePdoOneRepo;

/**
 * Generated by PdoOne Version 1.37
 * @copyright (c) Jorge Castro C. MIT License  https://github.com/EFTEC/PdoOne
 * Class PlayersRepo
 */
class PlayersRepo extends _BasePdoOneRepo
{
    const TABLE = 'players';
    const PK = 'ID';
    const ME=__CLASS__;

    public static function getDef() {
        return [
            'ID' => 'int not null auto_increment',
            'Name' => 'varchar(50)',
            'IdCounty' => 'int',
            'IsActive' => 'int'
        ];
    }
    public static function getDefKey() {
        return [
            'ID' => 'PRIMARY KEY',
            'IdCounty' => 'KEY'
        ];
    }
    public static function getDefFK($structure=false) {
        if ($structure) {
            return [
                'IdCounty' => 'FOREIGN KEY REFERENCES`country`(`IdCounty`)'
            ];
        }
        /* key,refcol,reftable,extra */
        return [
            'IdCounty' => [
                'key' => 'FOREIGN KEY',
                'refcol' => 'IdCounty',
                'reftable' => 'country',
                'extra' => 'FOREIGN KEY REFERENCES`country`(`IdCounty`)'
            ]
        ];
    }
    public static function factory() {
        $recursive=static::getRecursive();
        return [
            'ID'=>0,
            'Name'=>'',
            'IdCounty'=>0,
            '/country'=>(in_array('/country',$recursive))
                ? countryRepo::factory()
                : null, /* manytoone */
            'IsActive'=>0
        ];
    }
    public static function factoryNull() {
        return [
            'ID'=>null,
            'Name'=>null,
            'IdCounty'=>null,
            'IsActive'=>null
        ];
    }

}